function [fitresult, gof] = createFit(t, line)
%CREATEFIT(T,LINE)
%  Create a fit.
%
%  Data for 'theta' fit:
%      X Input : t
%      Y Output: line
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jun-2021 21:44:48


%% Fit: 'theta'.
% idx=t<.35&t>0.07;
% t1=t(idx);
% line1=line(idx);
[xData, yData] = prepareCurveData( t, line );

% Set up fittype and options.
ft = fittype( ['(a * (sin(2*pi*(w*t+d))+1)+b) * exp(-abs(t)/t1) + c *' ...
    ' exp(-(t) ^2/t2^2)'], 'independent', 't', 'dependent', 'line' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%                   a       b       c       d       t1      t2      w
opts.Lower = [      0.01    0       0       0       -Inf    -0.05   5];
opts.Upper = [      Inf     Inf     Inf     .5      Inf     0.05    10];
opts.StartPoint = [ 1       0.2     1       0.25    0.8     0.03    7.5];
opts.MaxFunEvals = 1600;
opts.MaxIter = 4000;
opts.TolFun = 1e-08;
opts.TolX = 1e-08;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'theta' );
% h = plot( fitresult, xData, yData );
% legend( h, 'line vs. t', 'theta', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'line', 'Interpreter', 'none' );
% grid on


