function [fitresult, gof] = createFit(t, line)
%CREATEFIT(T,LINE)
%  Create a fit.
%
%  Data for 'theta' fit:
%      X Input : t
%      Y Output: line
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jun-2021 21:44:48


%% Fit: 'theta'.
[xData, yData] = prepareCurveData( t, line );

% Set up fittype and options.
ft = fittype( '(a * (sin(2*pi*(w*t+d))+1)+b) * exp(-abs(t)/t1) + c * exp(-(t) ^2/t2^2)', 'independent', 't', 'dependent', 'line' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.01 -Inf -Inf -Inf -Inf -0.05 6];
opts.MaxFunEvals = 1600;
opts.MaxIter = 4000;
opts.StartPoint = [0.9991 0.171121066356432 1 0.56119979270966 0.88186650045181 0.03 8];
opts.TolFun = 1e-08;
opts.TolX = 1e-08;
opts.Upper = [Inf Inf Inf Inf Inf 0.05 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'theta' );
% h = plot( fitresult, xData, yData );
% legend( h, 'line vs. t', 'theta', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'line', 'Interpreter', 'none' );
% grid on


